name: build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-8 libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libopenal-dev mesa-common-dev
    - name: Build
      run: |
        Tools/linux/premake5 gmake2
        cd build
        make $* CC=gcc-8 CPP=g++-8 CXX=g++-8 CC=gcc-8

