name: build

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-8 libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libopenal-dev mesa-common-dev
    - name: Build gcc
      run: |
        Tools/linux/premake5 gmake2
        cd build
        make $* CC=gcc-8 CPP=g++-8 CXX=g++-8 CC=gcc-8 -j8
  MacOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        gem install xcpretty
        Tools/premake5 xcode4
        xcodebuild -project build/Sandbox.xcodeproj | xcpretty

  iOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        Tools/premake5 --os=ios xcode4 
        xcodebuild -project build/Sandbox.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        
  Windows:
    runs-on: windows-2019
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Generate Project
        run: | 
          cd Scripts
          ./GenerateVS19.bat
      - name: Build x64 Debug
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=x64 /p:Configuration=Debug build/Lumos.sln
      - name: Build x64 Release
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" /p:Platform=x64 /p:Configuration=Release build/Lumos.sln

